# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Les divagations d'un geek !
email: alexandre.houplon@etudiant.univ-lille1.fr
permalink: /:month-:day-:year/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Petit Blog sans intérêt d'un étudiant en informatique, à vocation thérapeutique plus que d'autre chose.
  J'y parles de ce que je veux quand ça me chante. Mais qui sait, en vous perdant ici, vous tomberez peut-être sur une ou deux perles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: halex02
github_username:  halex02

# Build settings
markdown: kramdown
