# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexandre Moret
  url:               https://twitter.com/mdo
  email:             alexandre.houplon.etu@univ-lille.fr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
