# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         ''
url:                 https://halex02.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexandre Moret
  url:               https://twitter.com/mdo
  email:             alexandre.houplon.etu@univ-lille.fr

# Gems
plugins:
  - jekyll-paginate
  - jekyll-github-metadata

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
